### ISSUE TITLE
Add Features 

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/Chat-App#2]
# Chat-App
This is a Prototype of a web chat app, main aim of this project is to make an invitation based chat app.

**What can you do?**
- So you need to make a home page, there will be two option one will be public chat (which is implemented already) and other option will be private chat.
In that it will generate a random url (zhat.ml/randomstring) , by using that url anyone can connect to that private chat.

- Work on UI.

- Add features to send images/files etc and also include emoji options.

- Integrate giphy api to send gifs.

## How to Clone?

- Fork the repo or `git clone https://github.com/tanwanimohit/Chat-App.git`
- To run it just type `node index.js`

**Comment by kushaggarwal** [comment]
I would like to work on this

**Comment by tanwanimohit** [comment]
> I would like to work on this

Go ahead :+1:

**Comment by kushaggarwal** [comment]
Okay Thank you

**Comment by kushaggarwal** [comment]
Can you please assign this to me if you don't mind

**Comment by tanwanimohit** [comment]
> Can you please assign this to me if you don't mind

@kushaggarwal Actually this issue is open for all, i cannot assign you ! As there are multiple things to be done .

**Comment by kushaggarwal** [comment]
Okay no problem

**Comment by tanwanimohit** [comment]
That's it for now!
